controller_manager_ns: '/'
controller_list:
  - name: arm_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
       - arm_joint_1
       - arm_joint_2
       - arm_joint_3
       - arm_joint_4
       - arm_joint_5
       - arm_joint_6
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - finger_joint_1
#      - finger_joint_2
#      - finger_joint_3

