controller_manager_ns: '/'
controller_list:
  - name: arm_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
       - Joint_1
       - Joint_2
       - Joint_3
       - Joint_4
       - Joint_5
       - Joint_6
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - Joint_7
#      - finger_joint_2
#      - finger_joint_3

