controller_list:
  - name: fake_arm_controller
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
      - arm_joint_6
  - name: fake_gripper_controller
    joints:
      - finger_joint_1
      - finger_joint_2
      - finger_joint_3
