joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint1
    - Joint2
    - Joint3
    - Joint4
    - Joint5
    - Joint6
  constraints:
    goal_time: 5.0
#          stopped_velocity_tolerance: 0.0
    Joint1: {trajectory: 0.0, goal: 0.0}
    Joint2: {trajectory: 0.0, goal: 0.0}
    Joint3: {trajectory: 0.0, goal: 0.0}
    Joint4: {trajectory: 0.0, goal: 0.0}
    Joint5: {trajectory: 0.0, goal: 0.0}
    Joint6: {trajectory: 0.0, goal: 0.0}
    gains:
      Joint1: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
      Joint2: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
      Joint3: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
      Joint4: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
      Joint5: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
      Joint6: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
#  stop_trajectory_duration: 1.0
#  allow_partial_joints_goal: true

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - FJoint1
#    - finger_joint_2
#    - finger_joint_3
  constraints:
    goal_time: 5.0
#    stopped_velocity_tolerance: 0.0
    FJoint1: {trajectory: 0.0, goal: 0.0}
#    finger_joint_2: {trajectory: 0.6, goal: 0.0}
#    finger_joint_3: {trajectory: 0.6, goal: 0.0}
    gains:
      FJoint1: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
#      finger_joint_2: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
#      finger_joint_3: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
#  stop_trajectory_duration: 1.0
  allow_partial_joints_goal: true
