joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
    - arm_joint_6
  constraints:
    goal_time: 5.0
    #      stopped_velocity_tolerance: 0.0
    arm_joint_1: {trajectory: 0.0, goal: 0.0}
    arm_joint_2: {trajectory: 0.0, goal: 0.0}
    arm_joint_3: {trajectory: 0.0, goal: 0.0}
    arm_joint_4: {trajectory: 0.0, goal: 0.0}
    arm_joint_5: {trajectory: 0.0, goal: 0.0}
    arm_joint_6: {trajectory: 0.0, goal: 0.0}
    gains:
      arm_1_joint: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
      arm_2_joint: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
      arm_3_joint: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
      arm_4_joint: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
      arm_5_joint: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
      arm_6_joint: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
#  stop_trajectory_duration: 1.0
#  allow_partial_joints_goal: true

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - finger_joint_1
#    - finger_joint_2
#    - finger_joint_3
  constraints:
    goal_time: 5.0
#    stopped_velocity_tolerance: 0.0
    finger_joint_1: {trajectory: 0.0, goal: 0.0}
#    finger_joint_2: {trajectory: 0.6, goal: 0.0}
#    finger_joint_3: {trajectory: 0.6, goal: 0.0}
    gains:
      finger_joint_1: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
#      finger_joint_2: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
#      finger_joint_3: {p: 10.0,  i: 1.0, d: 0.01, i_clamp: 1}
#  stop_trajectory_duration: 1.0
  allow_partial_joints_goal: true
