controller_list:
  - name: fake_arm_controller
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
  - name: fake_gripper_controller
    joints:
      - Joint_7